backend/controllers/PassportController.php
<?php
/**
 * @link http://www.u-bo.com
 * @copyright 南京友博网络科技有限公司 
 * @license http://www.u-bo.com/license/
 */

namespace backend\controllers;

use Yii;
use common\models\LoginForm;
use backend\models\Admin;

/**
 * 后台登录通行控制器
 * 
 * @author legendjw <legendjww@gmail.com>
 * @since 0.1
 */
class PassportController extends \yii\web\Controller
{
    /**
     * 用户登录
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        $model->userClass = Admin::className();

        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goHome();
        } else {
            return $this->renderPartial('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * 用户退出
     */
    public function actionLogout()
    {
        if (!Yii::$app->user->isGuest) {
            Yii::$app->user->logout();
        }
        return $this->goHome();
    }

}

backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\filters\AccessControl;
use common\models\LoginForm;
use yii\filters\VerbFilter;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * 首页框架
     */
    public function actionIndex()
    {
        return $this->renderPartial('index');
    }

    /**
     * 首页面板
     */
    public function actionPanel()
    {
        return $this->render('panel');
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending email.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->getSession()->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->getSession()->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->getSession()->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}

backend/views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

backend/views/site/index.php
<?php
use backend\assets\FrameAsset;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this \yii\web\View */
/* @var $content string */

FrameAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>

    <script>
        if (window.top !== window.self) {
            document.write = '';
            window.top.location.href = window.self.location.href;
            setTimeout(function () {
                document.body.innerHTML = '';
            }, 0);
        }
var SUBMENU = {
"custom":{"id":"custom","name":"系统","icon":"","tip":"","parent":"root","top":"","items":{"custom_set":{"id":"custom_set","name":"用户管理","icon":"","tip":"","parent":"custom","top":"","url":"","items":{"custom_set":{"id":"custom_set","name":"用户列表","icon":"","tip":"","parent":"custom","top":"","url":"admin.php?r=admin/index"},"custom_set1":{"id":"custom_set","name":"新增用户","icon":"","tip":"","parent":"custom","top":"","url":"admin.php?r=admin/create"}  }}}}
};
    </script>

    <?php $this->head() ?>

    <style>
        .fullScreen .content th{display:none;width:0;}
        .fullScreen .head,.fullScreen .tab{height:0;display:none;}
        .fullScreen #default{*left:0;*top:-90px;}
        .fullScreen div.options{top:0;}
    </style>
</head>
<body>
    <?php $this->beginBody() ?>

    <div class="wrap">
        <noscript><h1 class="noscript">您已禁用脚本，这样会导致页面不可用，请启用脚本后刷新页面</h1></noscript>
        <table width="100%" height="100%" style="table-layout:fixed;">
            <tr class="head">
                <th><a href="" class="logo">管理中心</a></th>
                <td>
                    <div class="nav">
                        <!-- 菜单异步获取，采用json格式，由js处理菜单展示结构 -->
                        <ul id="J_B_main_block">

                        </ul>
                    </div>
                    <div class="login_info">
                    <a href="" class="home" target="_blank">前台首页</a><span class="mr10">管理员： admin</span><a href="<?= Url::to(['passport/logout']) ?>" class="mr10">[注销]</a>
                </div></td>
            </tr>
            <tr class="tab">
                <th>
                    <div class="search">
                        <input size="15" placeholder="" id="J_search_keyword" type="text">
                        <button type="button" name="keyword" id="J_search" value="" data-url="">搜索</button>
                </div></th>
                <td>
                    <div id="B_tabA" class="tabA">
                        <a href="" tabindex="-1" class="tabA_pre" id="J_prev" title="上一页">上一页</a>
                        <a href="" tabindex="-1" class="tabA_next" id="J_next" title="下一页">下一页</a>
                        <div style="margin:0 25px;min-height:1px;">
                            <div style="position:relative;height:30px;width:100%;overflow:hidden;">
                                <ul id="B_history" style="white-space:nowrap;position:absolute;left:0;top:0;">
                                    <li class="current" data-id="default" tabindex="0"><span><a>后台首页</a></span></li>
                                </ul>
                            </div>
                        </div>
                </div></td>
            </tr>
            <tr class="content">
                <th  style="overflow:hidden;">
                    <div id="B_menunav">
                        <div class="menubar">
                            <dl id="B_menubar">
                                <dt class="disabled"></dt>
                            </dl>
                        </div>
                        <div id="menu_next" class="menuNext" style="display:none;">
                            <a href="" class="pre" title="顶部超出，点击向下滚动">向下滚动</a>
                            <a href="" class="next" title="高度超出，点击向上滚动">向上滚动</a>
                        </div>
                    </div>
                </th>
                <td id="B_frame">
                    <div id="breadCrumb" style="display:none;">
                        首页<em>&gt;</em>功能<em>&gt;</em>功能
                    </div>
                    <div class="options">
                        <a href="" class="refresh" id="J_refresh" title="刷新">刷新</a>
                        <a href="" id="J_fullScreen" class="full_screen" title="全屏">全屏</a>
                    </div>
                    <div class="loading" id="loading">加载中...</div>
                    <iframe id="iframe_default" src="<?= Url::to(['panel']) ?>" style="height: 100%; width: 100%;display:none;" data-id="default" frameborder="0" scrolling="auto"></iframe>
                </td>
            </tr>
        </table>
    </div>

    <?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

backend/views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
                <?= $form->field($model, 'username') ?>
                <?= $form->field($model, 'password')->passwordInput() ?>
                <?= $form->field($model, 'rememberMe')->checkbox() ?>
                <div class="form-group">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

backend/views/site/panel.php
hello